# Generated by Django 5.1 on 2024-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='fatura',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valorEmprestimo',
            field=models.CharField(max_length=15),
        ),
    ]
